import {KeyBindingsType, languages, mySandboxes, SeeingType} from "./types";

export const TITLE = "Go Sandbox";
export const LANGUAGE_GO = "go";

export const EVENT_STDOUT = "stdout";
export const EVENT_STDERR = "stderr";
export const EVENT_ERROR = "error";
export const EVENT_CLEAR = "clear";
export const EVENT_DONE = "done";

export const VIM = "vim"
export const EMACS = "emacs"
export const NONE = ""

export const SANDBOX_NAMES_KEY = "sandboxNames";
export const ACTIVE_SANDBOX_KEY = "activeSandbox";
export const IS_VERTICAL_LAYOUT_KEY = "isVerticalLayout";
export const GO_VERSION_KEY = "sandboxVersion";
export const KEY_BINDINGS_KEY = "keyBindings";
export const LANGUAGE_KEY = "languageKey";
export const IS_LINT_ON_KEY = "isLintOn";
export const IS_AUTOCOMPLETION_ON_KEY = "isAutoCompletionOn";
export const EDITOR_SIZE_KEY = "editorSize";
export const FONT_SIZE_KEY = "fontSize";
export const CURSOR_HEAD_KEY = "cursorHead";

export const DEFAULT_MAIN_FILE_PATH = "/main.go"
export const DEFAULT_INDENTATION_SIZE = 4;
export const DEFAULT_CURSOR_HEAD = 0;
export const DEFAULT_IS_VERTICAL_LAYOUT = "false";
export const DEFAULT_GO_VERSION = "1";
export const DEFAULT_KEY_BINDINGS: KeyBindingsType = "";
export const DEFAULT_LINT_ON = "true";
export const DEFAULT_AUTOCOMPLETION_ON = "true";
export const DEFAULT_EDITOR_SIZE = 50;
export const EDITOR_SIZE_MAX = 90
export const EDITOR_SIZE_MIN = 10
export const DEFAULT_LANGUAGE = "en";
export const FONT_SIZE_L = 15;
export const FONT_SIZE_M = 13;
export const FONT_SIZE_S = 11;
export const DEFAULT_ACTIVE_SANDBOX = "my-sandbox-1";

export const MOBILE_WIDTH = 768;

export const KEEP_ALIVE_INTERVAL = 30000;
export const DEBOUNCE_TIME = 75;
export const ACTIVE_COLOR = "cyan"
export const SELECTED_COLOR_CLASS = "font-semibold bg-gray-100 dark:bg-gray-600"
export const ICON_BUTTON_CLASS = "cursor-pointer hover:text-cyan-500 text-gray-600 dark:hover:text-cyan-400 dark:text-gray-300"
export const INACTIVE_TEXT_CLASS = "text-gray-300 dark:text-gray-600"

export const SNIPPET_REGEX = /\/snippets\/([a-zA-Z0-9-_]+)/g; // url base64 encoded
export const STATS_INFO_PREFIX = "STATS_INFO:"

export const HTTP_INTERNAL_ERROR = 500
export const HTTP_NOT_FOUND = 404

export const GO_VERSION_MAP: Record<string, string> = {
    "1": "Go 1.24",
    "2": "Go 1.23",
    "4": "Go dev branch",
}

export const LANGUAGES: { value: languages, label: string }[] = [
    {value: "en", label: "English"},
    {value: "zh_CN", label: "简体中文"},
    {value: "zh_TW", label: "繁體中文"},
    {value: "ja", label: "日本語"},
    {value: "ko", label: "한국어"},
    {value: "fr", label: "Français"},
    {value: "de", label: "Deutsch"},
    {value: "es", label: "Español"},
    {value: "it", label: "Italiano"},
    {value: "ru", label: "Русский"},
    {value: "hi", label: "हिन्दी"},
    {value: "pt_BR", label: "Português (Brasil)"},
    {value: "pt_PT", label: "Português (Portugal)"},
    {value: "vi", label: "Tiếng Việt"},
    {value: "th", label: "ภาษาไทย"},
    {value: "tr", label: "Türkçe"},
]
export const HELLO_WORLD = `package main

import "fmt"

func main() {
	fmt.Println("Hello, Go Sandbox!")
}`

export const TRANSLATE: Record<string, Record<languages, string>> = {
    nextPlace: {
        en: "Next Place",
        zh_CN: "下一个位置",
        zh_TW: "下一個位置",
        ja: "次の場所",
        ko: "다음 위치",
        fr: "Prochain endroit",
        de: "Nächster Ort",
        es: "Siguiente lugar",
        it: "Prossimo posto",
        ru: "Следующее место",
        hi: "अगला स्थान",
        pt_BR: "Próximo lugar",
        pt_PT: "Próximo lugar",
        vi: "Nơi tiếp theo",
        th: "สถานที่ถัดไป",
        tr: "Sonraki yer",
    },
    prevPlace: {
        en: "Previous Place",
        zh_CN: "上一个位置",
        zh_TW: "上一個位置",
        ja: "前の場所",
        ko: "이전 위치",
        fr: "Endroit précédent",
        de: "Vorheriger Ort",
        es: "Lugar anterior",
        it: "Posto precedente",
        ru: "Предыдущее место",
        hi: "पिछला स्थान",
        pt_BR: "Lugar anterior",
        pt_PT: "Lugar anterior",
        vi: "Nơi trước",
        th: "สถานที่ก่อนหน้า",
        tr: "Önceki yer",
    },
    implementations: {
        en: "See implementations",
        zh_CN: "查看实现",
        zh_TW: "查看實現",
        ja: "実装を表示",
        ko: "구현 보기",
        fr: "Voir les implémentations",
        de: "Implementierungen anzeigen",
        es: "Ver implementaciones",
        it: "Vedi implementazioni",
        ru: "Посмотреть реализации",
        hi: "कार्यान्वयन देखें",
        pt_BR: "Ver implementações",
        pt_PT: "Ver implementações",
        vi: "Xem triển khai",
        th: "ดูการใช้งาน",
        tr: "Uygulamaları gör",
    },
    usages: {
        en: "See usages",
        zh_CN: "查看引用",
        zh_TW: "查看引用",
        ja: "参照を表示",
        ko: "사용법 보기",
        fr: "Voir les usages",
        de: "Verwenden Sie die Implementierungen",
        es: "Ver usos",
        it: "Vedi usi",
        ru: "Посмотреть использования",
        hi: "उपयोग देखें",
        pt_BR: "Ver usos",
        pt_PT: "Ver usos",
        vi: "Xem cách sử dụng",
        th: "ดูการใช้งาน",
        tr: "Kullanımları gör",
    },
    definitions: {
        en: "See definition",
        zh_CN: "查看定义",
        zh_TW: "查看定義",
        ja: "定義を表示",
        ko: "정의 보기",
        fr: "Voir la définition",
        de: "Definition anzeigen",
        es: "Ver definición",
        it: "Vedi definizione",
        ru: "Посмотреть определение",
        hi: "परिभाषा देखें",
        pt_BR: "Ver definição",
        pt_PT: "Ver definição",
        vi: "Xem định nghĩa",
        th: "ดูการกำหนด",
        tr: "Tanımı gör",
    },
    suggestCompletion: {
        en: "See completions",
        zh_CN: "查看补全",
        zh_TW: "查看補全",
        ja: "補完を表示",
        ko: "완성 보기",
        fr: "Voir les complétions",
        de: "Vervollständigungen anzeigen",
        es: "Ver completaciones",
        it: "Vedi completamenti",
        ru: "Посмотреть завершения",
        hi: "पूर्णता देखें",
        pt_BR: "Ver conclusões",
        pt_PT: "Ver conclusões",
        vi: "Xem hoàn thành",
        th: "ดูการเติมเต็ม",
        tr: "Tamamlamaları gör",
    },
    foldAll: {
        en: "Fold All",
        zh_CN: "折叠全部",
        zh_TW: "折疊全部",
        ja: "すべて折りたたむ",
        ko: "모두 접기",
        fr: "Tout plier",
        de: "Alles falten",
        es: "Doblar todo",
        it: "Piegare tutto",
        ru: "Сложить все",
        hi: "सभी को मोड़ें",
        pt_BR: "Dobre tudo",
        pt_PT: "Dobre tudo",
        vi: "Gấp tất cả",
        th: "พับทั้งหมด",
        tr: "Hepsini katla",
    },
    foldCode: {
        en: "Fold Code",
        zh_CN: "折叠代码",
        zh_TW: "折疊代碼",
        ja: "コードを折りたたむ",
        ko: "코드 접기",
        fr: "Plier le code",
        de: "Code falten",
        es: "Plegar código",
        it: "Piegare codice",
        ru: "Сложить код",
        hi: "कोड मोड़ें",
        pt_BR: "Dobre o código",
        pt_PT: "Dobre o código",
        vi: "Gấp mã",
        th: "พับรหัส",
        tr: "Kodu katla",
    },
    unfoldAll: {
        en: "Unfold All",
        zh_CN: "展开全部",
        zh_TW: "展開全部",
        ja: "すべて展開する",
        ko: "모두 펼치기",
        fr: "Tout déplier",
        de: "Alles entfalten",
        es: "Desplegar todo",
        it: "Espandi tutto",
        ru: "Развернуть все",
        hi: "सभी को खोलें",
        pt_BR: "Desdobre tudo",
        pt_PT: "Desdobre tudo",
        vi: "Mở tất cả",
        th: "คลายทั้งหมด",
        tr: "Hepsini aç",
    },
    unfoldCode: {
        en: "Unfold Code",
        zh_CN: "展开代码",
        zh_TW: "展開代碼",
        ja: "コードを展開する",
        ko: "코드 펼치기",
        fr: "Déplier le code",
        de: "Code entfalten",
        es: "Desplegar código",
        it: "Espandi codice",
        ru: "Развернуть код",
        hi: "कोड खोलें",
        pt_BR: "Desdobre o código",
        pt_PT: "Desdobre o código",
        vi: "Mở mã",
        th: "คลายรหัส",
        tr: "Kodu aç",
    },
    nextDiagnostic: {
        en: "Next Diagnostic",
        zh_CN: "下一个提示",
        zh_TW: "下一個提示",
        ja: "次の診断",
        ko: "다음 진단",
        fr: "Prochain diagnostic",
        de: "Nächste Diagnose",
        es: "Siguiente diagnóstico",
        it: "Prossimo diagnostico",
        ru: "Следующая диагностика",
        hi: "अगली डायग्नोस्टिक",
        pt_BR: "Próxima avaliação",
        pt_PT: "Próxima avaliação",
        vi: "Chẩn đoán tiếp theo",
        th: "การวินิจฉัยถัดไป",
        tr: "Sonraki tanı",
    },
    openLintPanel: {
        en: "Open Lint Panel",
        zh_CN: "打开提示面板",
        zh_TW: "打開提示面板",
        ja: "リントパネルを開く",
        ko: "린트 패널 열기",
        fr: "Ouvrir le panneau de lint",
        de: "Lint-Panel öffnen",
        es: "Abrir panel de lint",
        it: "Apri il pannello di lint",
        ru: "Открыть панель линтинга",
        hi: "लिंट पैनल खोलें",
        pt_BR: "Abrir painel de lint",
        pt_PT: "Abrir painel de lint",
        vi: "Mở bảng điều khiển lint",
        th: "เปิดแผงลินท์",
        tr: "Lint panelini aç",
    },
    search: {
        en: "Search",
        zh_CN: "搜索",
        zh_TW: "搜尋",
        ja: "検索",
        ko: "검색",
        fr: "Recherche",
        de: "Suche",
        es: "Buscar",
        it: "Cerca",
        ru: "Поиск",
        hi: "खोजें",
        pt_BR: "Pesquisar",
        pt_PT: "Pesquisar",
        vi: "Tìm kiếm",
        th: "ค้นหา",
        tr: "Ara",
    },
    theme: {
        en: "Theme",
        zh_CN: "主题",
        zh_TW: "主題",
        ja: "テーマ",
        ko: "테마",
        fr: "Thème",
        de: "Thema",
        es: "Tema",
        it: "Tema",
        ru: "Тема",
        hi: "थीम",
        pt_BR: "Tema",
        pt_PT: "Tema",
        vi: "Chủ đề",
        th: "ธีม",
        tr: "Tema",
    },
    layout: {
        en: "Layout",
        zh_CN: "布局",
        zh_TW: "佈局",
        ja: "レイアウト",
        ko: "레이아웃",
        fr: "Mise en page",
        de: "Layout",
        es: "Diseño",
        it: "Layout",
        ru: "Макет",
        hi: "लेआउट",
        pt_BR: "Layout",
        pt_PT: "Layout",
        vi: "Bố cục",
        th: "เค้าโครง",
        tr: "Düzen",
    },
    run: {
        en: "Run",
        zh_CN: "运行",
        zh_TW: "執行",
        ja: "実行",
        ko: "실행",
        fr: "Exécuter",
        de: "Ausführen",
        es: "Ejecutar",
        it: "Esegui",
        ru: "Запустить",
        hi: "चलाएँ",
        pt_BR: "Executar",
        pt_PT: "Executar",
        vi: "Chạy",
        th: "เรียกใช้",
        tr: "Çalıştır",
    },
    running: {
        en: "Running...",
        zh_CN: "运行中...",
        zh_TW: "執行中...",
        ja: "実行中...",
        ko: "실행 중...",
        fr: "En cours d'exécution...",
        de: "Wird ausgeführt...",
        es: "Ejecutando...",
        it: "In esecuzione...",
        ru: "Запуск...",
        hi: "चल रहा है...",
        pt_BR: "Executando...",
        pt_PT: "Executando...",
        vi: "Đang chạy...",
        th: "กำลังทำงาน...",
        tr: "Çalışıyor...",
    },
    format: {
        en: "Format",
        zh_CN: "格式化",
        zh_TW: "格式化",
        ja: "フォーマット",
        ko: "형식 지정",
        fr: "Format",
        de: "Format",
        es: "Formato",
        it: "Formato",
        ru: "Формат",
        hi: "स्वरूप",
        pt_BR: "Formato",
        pt_PT: "Formato",
        vi: "Định dạng",
        th: "รูปแบบ",
        tr: "Biçim",
    },
    share: {
        en: "Share",
        zh_CN: "分享",
        zh_TW: "分享",
        ja: "共有",
        ko: "공유",
        fr: "Partager",
        de: "Teilen",
        es: "Compartir",
        it: "Condividi",
        ru: "Поделиться",
        hi: "साझा करें",
        pt_BR: "Compartilhar",
        pt_PT: "Compartilhar",
        vi: "Chia sẻ",
        th: "แบ่งปัน",
        tr: "Paylaş",
    },
    new: {
        en: "New",
        zh_CN: "新建",
        zh_TW: "新建",
        ja: "新規作成",
        ko: "새로 만들기",
        fr: "Nouveau",
        de: "Neu",
        es: "Nuevo",
        it: "Nuovo",
        ru: "Новый",
        hi: "नया",
        pt_BR: "Novo",
        pt_PT: "Novo",
        vi: "Mới",
        th: "ใหม่",
        tr: "Yeni",
    },
    settings: {
        en: "Settings",
        zh_CN: "设置",
        zh_TW: "設置",
        ja: "設定",
        ko: "설정",
        fr: "Paramètres",
        de: "Einstellungen",
        es: "Configuraciones",
        it: "Impostazioni",
        ru: "Настройки",
        hi: "सेटिंग्स",
        pt_BR: "Configurações",
        pt_PT: "Configurações",
        vi: "Cài đặt",
        th: "การตั้งค่า",
        tr: "Ayarlar",
    },
    hintManual: {
        en: "Press 'Run' to execute",
        zh_CN: "按运行键以执行",
        zh_TW: "按執行鍵以執行",
        ja: "実行するには実行を押してください",
        ko: "실행하려면 실행을 누르세요",
        fr: "Appuyez sur 'Exécuter' pour exécuter",
        de: "Drücken Sie 'Ausführen', um auszuführen",
        es: "Presione 'Ejecutar' para ejecutar",
        it: "Premi 'Esegui' per eseguire",
        ru: "Нажмите 'Запустить', чтобы выполнить",
        hi: "'चलाएँ' पर क्लिक करें",
        pt_BR: "Pressione 'Executar' para executar",
        pt_PT: "Pressione 'Executar' para executar",
        vi: "Nhấn 'Chạy' để thực thi",
        th: "'เรียกใช้' เพื่อดำเนินการ",
        tr: "Çalıştırmak için 'Çalıştır'ı basın",
    },
    language: {
        en: "Language",
        zh_CN: "语言",
        zh_TW: "語言",
        ja: "言語",
        ko: "언어",
        fr: "Langue",
        de: "Sprache",
        es: "Idioma",
        it: "Lingua",
        ru: "Язык",
        hi: "भाषा",
        pt_BR: "Idioma",
        pt_PT: "Idioma",
        vi: "Ngôn ngữ",
        th: "ภาษา",
        tr: "Dil",
    },
    fontSize: {
        en: "Font Size",
        zh_CN: "字体大小",
        zh_TW: "字體大小",
        ja: "フォントサイズ",
        ko: "글꼴 크기",
        fr: "Taille de police",
        de: "Schriftgröße",
        es: "Tamaño de fuente",
        it: "Dimensione del carattere",
        ru: "Размер шрифта",
        hi: "फॉन्ट का आकार",
        pt_BR: "Tamanho da fonte",
        pt_PT: "Tamanho da fonte",
        vi: "Kích thước phông chữ",
        th: "ขนาดฟอนต์",
        tr: "Yazı tipi boyutu",
    },
    keyBindings: {
        en: "Key Bindings",
        zh_CN: "键位设置",
        zh_TW: "鍵位設置",
        ja: "キーバインディング",
        ko: "키 바인딩",
        fr: "Raccourcis clavier",
        de: "Tastenkombinationen",
        es: "Asignaciones de teclas",
        it: "Assegnazioni tasti",
        ru: "Назначения клавиш",
        hi: "कुंजी बाइंडिंग",
        pt_BR: "Vinculações de teclas",
        pt_PT: "Vinculações de teclas",
        vi: "Liên kết phím",
        th: "การผูกปุ่ม",
        tr: "Klavye kısayolları",
    },
    lint: {
        en: "Lint",
        zh_CN: "提示",
        zh_TW: "提示",
        ja: "リント",
        ko: "린트",
        fr: "Lint",
        de: "Lint",
        es: "Lint",
        it: "Lint",
        ru: "Линт",
        hi: "लिंट",
        pt_BR: "Lint",
        pt_PT: "Lint",
        vi: "Lint",
        th: "Lint",
        tr: "Lint",
    },
    autoCompletion: {
        en: "Auto Completion",
        zh_CN: "自动补全",
        zh_TW: "自動補全",
        ja: "自動補完",
        ko: "자동 완성",
        fr: "Auto-complétion",
        de: "Automatische Vervollständigung",
        es: "Autocompletar",
        it: "Completamento automatico",
        ru: "Автозаполнение",
        hi: "स्वचालित पूर्णता",
        pt_BR: "Autocompletar",
        pt_PT: "Autocompletar",
        vi: "Tự động hoàn thành",
        th: "การเติมอัตโนมัติ",
        tr: "Otomatik tamamlama",
    },
    rename: {
        en: "Rename",
        zh_CN: "重命名",
        zh_TW: "重命名",
        ja: "名前を変更",
        ko: "이름 바꾸기",
        fr: "Renommer",
        de: "Umbenennen",
        es: "Renombrar",
        it: "Rinomina",
        ru: "Переименовать",
        hi: "नाम बदलें",
        pt_BR: "Renomear",
        pt_PT: "Renomear",
        vi: "Đổi tên",
        th: "เปลี่ยนชื่อ",
        tr: "Yeniden adlandır",
    },
    remove: {
        en: "Remove",
        zh_CN: "删除",
        zh_TW: "刪除",
        ja: "削除",
        ko: "제거",
        fr: "Supprimer",
        de: "Entfernen",
        es: "Eliminar",
        it: "Rimuovi",
        ru: "Удалить",
        hi: "हटाएँ",
        pt_BR: "Remover",
        pt_PT: "Remover",
        vi: "Xóa",
        th: "ลบ",
        tr: "Kaldır",
    },
    reload: {
        en: "Reload",
        zh_CN: "刷新",
        zh_TW: "刷新",
        ja: "リロード",
        ko: "새로 고침",
        fr: "Recharger",
        de: "Neu laden",
        es: "Recargar",
        it: "Ricarica",
        ru: "Перезагрузить",
        hi: "पुनः लोड करें",
        pt_BR: "Recarregar",
        pt_PT: "Recarregar",
        vi: "Tải lại",
        th: "โหลดใหม่",
        tr: "Yenile",
    },
    manual: {
        en: "Manual",
        zh_CN: "手册",
        zh_TW: "手冊",
        ja: "マニュアル",
        ko: "매뉴얼",
        fr: "Manuel",
        de: "Handbuch",
        es: "Manual",
        it: "Manuale",
        ru: "Руководство",
        hi: "हस्तनिर्देश",
        pt_BR: "Manual",
        pt_PT: "Manual",
        vi: "Sổ tay",
        th: "คู่มือ",
        tr: "Kılavuz",
    },
    jumpTo: {
        en: "Jump to",
        zh_CN: "跳转到",
        zh_TW: "跳轉到",
        ja: "ジャンプする",
        ko: "이동하기",
        fr: "Aller à",
        de: "Gehe zu",
        es: "Saltar a",
        it: "Salta a",
        ru: "Перейти к",
        hi: "पर जाएं",
        pt_BR: "Pule para",
        pt_PT: "Pule para",
        vi: "Nhảy đến",
        th: "กระโดดไปที่",
        tr: "Atla",
    }
}

export const SNIPPETS: Record<string, Record<string, string>> = {
    Basic: {
        helloWorld: "Hello World",
        sleep: "Sleep",
        defer: "Defer",
        switchCase: "Switch-case",
        goroutine: "Goroutine",
        channel: "Channel",
        assertion: "Assertion",
        fileIO: "File I/O",
        contextCancel: "Context",
        json: "JSON",
        mutex: "Mutex",
        ticker: "Ticker",
    },
    Advanced: {
        spinner: "Spinner",
        progressBar: "Progress bar",
        httpServer: "HTTP server",
        gameOfLife: "Game of Life",
        concurrentPrime: "Concurrent prime",
        diningPhilosophers: "Dining philosophers",
        fibonacci: "Fibonacci",
        quickSort: "Quick sort",
        mergeSort: "Merge sort",
        binarySearch: "Binary search",
        sudoku: "Sudoku",
        maze: "Maze",
        bfs: "BFS",
        dfs: "DFS",
        lru: "LRU",
        lcs: "LCS",
    },
    "Design Patterns": {
        singleton: "Singleton",
        factory: "Factory",
        strategy: "Strategy",
        template: "Template",
        prototype: "Prototype",
        adaptor: "Adaptor",
        decorator: "Decorator",
        facade: "Facade",
        observer: "Observer",
        bridge: "Bridge",
        composite: "Composite",
        proxy: "Proxy",
    },
}

export const keyBindingsMap: Record<KeyBindingsType, string> = {
    vim: "Vim",
    emacs: "Emacs",
    "": "None",
}

export const MY_SANDBOXES: Record<mySandboxes, string> = {
    "my-sandbox-1": "Sandbox 1",
    "my-sandbox-2": "Sandbox 2",
    "my-sandbox-3": "Sandbox 3",
    "my-sandbox-4": "Sandbox 4",
    "my-sandbox-5": "Sandbox 5",
    "my-sandbox-6": "Sandbox 6",
    "my-sandbox-7": "Sandbox 7",
    "my-sandbox-8": "Sandbox 8",
    "my-sandbox-9": "Sandbox 9",
    "my-sandbox-10": "Sandbox 10",
}
export const BUTTON_INACTIVE = "cursor-not-allowed text-gray-300 dark:text-gray-700";

export const WORKSPACE = "workspace";
export const URI_BASE = `file:///${WORKSPACE}`

export const SEEING_USAGES: SeeingType = "usages"
export const SEEING_IMPLEMENTATIONS: SeeingType = "implementations"
